// Code generated by "stringer -type=Color -linecomment=true"; DO NOT EDIT.

package board

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[White-0]
	_ = x[Black-1]
}

const _Color_name = "wb"

var _Color_index = [...]uint8{0, 1, 2}

func (i Color) String() string {
	if i >= Color(len(_Color_index)-1) {
		return "Color(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Color_name[_Color_index[i]:_Color_index[i+1]]
}
