// Code generated by "stringer -type=Rank"; DO NOT EDIT.

package board

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Rank1-0]
	_ = x[Rank2-1]
	_ = x[Rank3-2]
	_ = x[Rank4-3]
	_ = x[Rank5-4]
	_ = x[Rank6-5]
	_ = x[Rank7-6]
	_ = x[Rank8-7]
}

const _Rank_name = "Rank1Rank2Rank3Rank4Rank5Rank6Rank7Rank8"

var _Rank_index = [...]uint8{0, 5, 10, 15, 20, 25, 30, 35, 40}

func (i Rank) String() string {
	if i >= Rank(len(_Rank_index)-1) {
		return "Rank(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Rank_name[_Rank_index[i]:_Rank_index[i+1]]
}
