// Code generated by "stringer -type=Role"; DO NOT EDIT.

package board

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Pawn-1]
	_ = x[Knight-2]
	_ = x[Bishop-3]
	_ = x[Rook-4]
	_ = x[Queen-5]
	_ = x[King-6]
}

const _Role_name = "PawnKnightBishopRookQueenKing"

var _Role_index = [...]uint8{0, 4, 10, 16, 20, 25, 29}

func (i Role) String() string {
	i -= 1
	if i >= Role(len(_Role_index)-1) {
		return "Role(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Role_name[_Role_index[i]:_Role_index[i+1]]
}
