// Code generated by "stringer -type=Square -linecomment=true"; DO NOT EDIT.

package board

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[A1-0]
	_ = x[B1-1]
	_ = x[C1-2]
	_ = x[D1-3]
	_ = x[E1-4]
	_ = x[F1-5]
	_ = x[G1-6]
	_ = x[H1-7]
	_ = x[A2-8]
	_ = x[B2-9]
	_ = x[C2-10]
	_ = x[D2-11]
	_ = x[E2-12]
	_ = x[F2-13]
	_ = x[G2-14]
	_ = x[H2-15]
	_ = x[A3-16]
	_ = x[B3-17]
	_ = x[C3-18]
	_ = x[D3-19]
	_ = x[E3-20]
	_ = x[F3-21]
	_ = x[G3-22]
	_ = x[H3-23]
	_ = x[A4-24]
	_ = x[B4-25]
	_ = x[C4-26]
	_ = x[D4-27]
	_ = x[E4-28]
	_ = x[F4-29]
	_ = x[G4-30]
	_ = x[H4-31]
	_ = x[A5-32]
	_ = x[B5-33]
	_ = x[C5-34]
	_ = x[D5-35]
	_ = x[E5-36]
	_ = x[F5-37]
	_ = x[G5-38]
	_ = x[H5-39]
	_ = x[A6-40]
	_ = x[B6-41]
	_ = x[C6-42]
	_ = x[D6-43]
	_ = x[E6-44]
	_ = x[F6-45]
	_ = x[G6-46]
	_ = x[H6-47]
	_ = x[A7-48]
	_ = x[B7-49]
	_ = x[C7-50]
	_ = x[D7-51]
	_ = x[E7-52]
	_ = x[F7-53]
	_ = x[G7-54]
	_ = x[H7-55]
	_ = x[A8-56]
	_ = x[B8-57]
	_ = x[C8-58]
	_ = x[D8-59]
	_ = x[E8-60]
	_ = x[F8-61]
	_ = x[G8-62]
	_ = x[H8-63]
}

const _Square_name = "a1b1c1d1e1f1g1h1a2b2c2d2e2f2g2h2a3b3c3d3e3f3g3h3a4b4c4d4e4f4g4h4a5b5c5d5e5f5g5h5a6b6c6d6e6f6g6h6a7b7c7d7e7f7g7h7a8b8c8d8e8f8g8h8"

var _Square_index = [...]uint8{0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128}

func (i Square) String() string {
	if i >= Square(len(_Square_index)-1) {
		return "Square(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Square_name[_Square_index[i]:_Square_index[i+1]]
}
