// Code generated by "stringer -type Piece"; DO NOT EDIT.

package chess

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WhitePawn-1]
	_ = x[WhiteKnight-2]
	_ = x[WhiteBishop-3]
	_ = x[WhiteRook-4]
	_ = x[WhiteQueen-5]
	_ = x[WhiteKing-6]
	_ = x[BlackPawn-9]
	_ = x[BlackKnight-10]
	_ = x[BlackBishop-11]
	_ = x[BlackRook-12]
	_ = x[BlackQueen-13]
	_ = x[BlackKing-14]
}

const (
	_Piece_name_0 = "WhitePawnWhiteKnightWhiteBishopWhiteRookWhiteQueenWhiteKing"
	_Piece_name_1 = "BlackPawnBlackKnightBlackBishopBlackRookBlackQueenBlackKing"
)

var (
	_Piece_index_0 = [...]uint8{0, 9, 20, 31, 40, 50, 59}
	_Piece_index_1 = [...]uint8{0, 9, 20, 31, 40, 50, 59}
)

func (i Piece) String() string {
	switch {
	case 1 <= i && i <= 6:
		i -= 1
		return _Piece_name_0[_Piece_index_0[i]:_Piece_index_0[i+1]]
	case 9 <= i && i <= 14:
		i -= 9
		return _Piece_name_1[_Piece_index_1[i]:_Piece_index_1[i+1]]
	default:
		return "Piece(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
