// Code generated by "stringer -type=CastlingRight"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WhiteOO-1]
	_ = x[WhiteOOO-2]
	_ = x[BlackOO-4]
	_ = x[BlackOOO-8]
}

const (
	_CastlingRight_name_0 = "WhiteOOWhiteOOO"
	_CastlingRight_name_1 = "BlackOO"
	_CastlingRight_name_2 = "BlackOOO"
)

var (
	_CastlingRight_index_0 = [...]uint8{0, 7, 15}
)

func (i CastlingRight) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _CastlingRight_name_0[_CastlingRight_index_0[i]:_CastlingRight_index_0[i+1]]
	case i == 4:
		return _CastlingRight_name_1
	case i == 8:
		return _CastlingRight_name_2
	default:
		return "CastlingRight(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
