// Code generated by "stringer -type File"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FileA-0]
	_ = x[FileB-1]
	_ = x[FileC-2]
	_ = x[FileD-3]
	_ = x[FileE-4]
	_ = x[FileF-5]
	_ = x[FileG-6]
	_ = x[FileH-7]
}

const _File_name = "FileAFileBFileCFileDFileEFileFFileGFileH"

var _File_index = [...]uint8{0, 5, 10, 15, 20, 25, 30, 35, 40}

func (i File) String() string {
	if i >= File(len(_File_index)-1) {
		return "File(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _File_name[_File_index[i]:_File_index[i+1]]
}
